FROM python:3.11-slim

WORKDIR /app

# Dependencies kur
COPY TestFiles/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Test dosyalarını kopyala
COPY TestFiles/ .

# Controller scripti çalıştır
CMD ["python", "controller.py"]